{% set name = "utilsforecast" %}
{% set version = "0.2.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 73f9dfd836a721a95c349f784bd75e18a4cb7c1469800e325414e22901e9775b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools >=36.2
  run:
    - python
    - numpy
    - packaging
    - pandas >=1.1.1

test:
  imports:
    - utilsforecast
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Nixtla/utilsforecast
  summary: Forecasting utilities
  license: Apache-2.0
  license_file: LICENSE
  license_family: APACHE
  description: Forecasting utilities
  dev_url: https://github.com/Nixtla/utilsforecast
  doc_url: https://nixtlaverse.nixtla.io/utilsforecast/index.html

extra:
  recipe-maintainers:
    - AzulGarza
    - jmoralez
